From 2251985/todobackend-base:latest
MAINTAINER Zohar Nyego <zoharngo@gmail.com>

# Install dev/build dependencies
RUN apt-get update && \
    apt-get install -qy gcc python-dev libmysqlclient-dev

# Activate virtual envirnoment and install wheel support
RUN . /appenv/bin/activate && \
    pip install wheel setuptools --upgrade

# PIP environment variables (NOTE: must be set after installtion wheel)
ENV WHEELHOUSE=/wheelhouse PIP_WHEEL_DIR=/wheelhouse PIP_FIND_LINKS=/wheelhouse XDG_CACHE_HOME=/cache

# OUTPUT: Build artefacts (Wheels) are output here
VOLUME /wheelhouse

# OUTPUT: Tests reports are output here
VOLUME /reports

# OUTPUT: Build cache
VOLUME /build

# Add test entrypoint script
COPY scripts/test.sh /usr/local/bin/test.sh
COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/test.sh

# Set defaults for entrypoint and command string
ENTRYPOINT ["test.sh"]
CMD ["python","manage.py","test","--noinput"]

# Add appilcation source
COPY src /application
WORKDIR /application

# Add permission to perform changes in application folder
RUN chmod -R o+rwx /application
