From zoharn/todobackend-base:latest
MAINTAINER Zohar Nyego <zoharngo@gmail.com>

# Install dev/build dependencies
RUN apt-get update && \
    apt-get install -qy python-dev

# Activate virtual envirnoment and install wheel support
RUN . /appenv/bin/activate && \
    pip install wheel --upgrade

# PIP environment variables (NOTE: must be set after installtion wheel)
ENV WHEELHOUSE=/wheelhouse PIP_WHEEL_DIR=/wheelhouse PIP_FIND_LINKS=/wheelhouse XDG_CACHE_HOME=/cache

# OUTPUT: Build artefacts (Wheels) are output here
VOLUME /wheelhouse

# OUTPUT: Tests reports are output here
VOLUME /reports

COPY scripts/test.sh /usr/local/bin/test.sh
RUN chmod +x /usr/local/bin/test.sh

# Set defaults for entrypoint and command string
ENTRYPOINT ["test.sh"]
CMD ["python","manage.py","test","--noinput"]


# Add appilcation source
COPY src /application
WORKDIR /application
